/**
 * Sitemap generator — writes `public/sitemap.xml` from the single authoritative
 * route inventory in `scripts/public-routes.mjs`.
 *
 * BD-ROUTE-AUTHORITY-01: replaces the previous vite-plugin-sitemap build step
 * and the hand-maintained `public/sitemap.xml`. Runs before `vite build` (see
 * package.json "build") so Vite copies the freshly generated file from
 * `public/` into `dist/` as the deployable artifact.
 *
 * After writing, the script re-parses its own output and fails (non-zero exit)
 * if the sitemap does not contain exactly the authoritative route set, if any
 * URL is duplicated, or if a non-production hostname (localhost / Vercel
 * preview) leaks in. That guard is what keeps the sitemap output and the
 * prerender input from diverging — both derive from the same authority.
 */

import { fileURLToPath } from 'url'
import path from 'path'
import fs from 'fs'
import { PUBLIC_ROUTES, ROUTE_PATHS, HOSTNAME, assertValidRoutes } from './public-routes.mjs'

const __dirname = path.dirname(fileURLToPath(import.meta.url))
const ROOT = path.resolve(__dirname, '..')
const OUTPUT = path.resolve(ROOT, 'public', 'sitemap.xml')

/** Build the absolute <loc> URL for a route path. */
function locFor(routePath) {
  // HOSTNAME has no trailing slash; "/" -> "https://host/", "/x" -> "https://host/x".
  return `${HOSTNAME}${routePath}`
}

function buildSitemapXml(routes) {
  const urls = routes
    .map(
      (r) =>
        [
          '  <url>',
          `    <loc>${locFor(r.path)}</loc>`,
          `    <changefreq>${r.changefreq}</changefreq>`,
          `    <priority>${r.priority}</priority>`,
          '  </url>',
        ].join('\n'),
    )
    .join('\n')

  return [
    '<?xml version="1.0" encoding="UTF-8"?>',
    '<!-- Generated by scripts/generate-sitemap.mjs from scripts/public-routes.mjs. Do not edit by hand. -->',
    '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">',
    urls,
    '</urlset>',
    '',
  ].join('\n')
}

/**
 * Re-parse the produced XML and assert it contains exactly the authoritative
 * route set — no more, no less, no duplicates, production hostname only.
 */
function validateSitemapOutput(xml) {
  const authorityPaths = new Set(ROUTE_PATHS)

  // Reject any non-production hostname before anything else.
  if (/localhost|127\.0\.0\.1|vercel\.app|\.vercel\./i.test(xml)) {
    throw new Error('Sitemap contains a non-production hostname (localhost / Vercel preview).')
  }

  const locs = [...xml.matchAll(/<loc>([^<]+)<\/loc>/g)].map((m) => m[1])

  const parsedPaths = locs.map((loc) => {
    if (!loc.startsWith(`${HOSTNAME}`)) {
      throw new Error(`Sitemap <loc> does not use the production hostname: ${loc}`)
    }
    const p = loc.slice(HOSTNAME.length)
    if (!p.startsWith('/')) {
      throw new Error(`Sitemap <loc> path must begin with "/": ${loc}`)
    }
    return p
  })

  // No duplicates in the output.
  const seen = new Set()
  for (const p of parsedPaths) {
    if (seen.has(p)) throw new Error(`Duplicate URL in sitemap output: ${p}`)
    seen.add(p)
  }

  // Exact set equality with the authority (sitemap output must not diverge
  // from the prerender input — both are the authority).
  const missing = ROUTE_PATHS.filter((p) => !seen.has(p))
  const extra = [...seen].filter((p) => !authorityPaths.has(p))
  if (missing.length || extra.length) {
    throw new Error(
      `Sitemap does not match the authoritative route set.` +
        (missing.length ? ` Missing: ${missing.join(', ')}.` : '') +
        (extra.length ? ` Unexpected: ${extra.join(', ')}.` : ''),
    )
  }

  if (parsedPaths.length !== ROUTE_PATHS.length) {
    throw new Error(
      `Sitemap URL count ${parsedPaths.length} != authoritative route count ${ROUTE_PATHS.length}.`,
    )
  }

  return parsedPaths.length
}

// 1. Validate the authority itself (dup paths, leading slash, freq/priority).
assertValidRoutes()

// 2. Build and write.
const xml = buildSitemapXml(PUBLIC_ROUTES)
fs.writeFileSync(OUTPUT, xml)

// 3. Self-validate the written artifact.
const count = validateSitemapOutput(fs.readFileSync(OUTPUT, 'utf-8'))

console.log(`🗺️  Generated ${path.relative(ROOT, OUTPUT)} with ${count} canonical URLs (${HOSTNAME}).`)
