-- Site authority for Maintenance lifecycle/action RPCs.

create or replace function public.pause_maintenance_relationship(target_relationship_id uuid,expected_version integer,reason text default null)
returns public.maintenance_relationships language plpgsql security definer set search_path=pg_catalog,public as $$
declare existing public.maintenance_relationships; clean_reason text:=nullif(trim(coalesce(reason,'')),''); scheduled_count integer;
begin select * into existing from public.maintenance_relationships where id=target_relationship_id for update; if not found then raise exception 'Maintenance relationship not found' using errcode='P0002'; end if; if not public.can_manage_maintenance_site(existing.site_id) then raise exception 'You are not authorised to manage this Maintenance relationship' using errcode='42501'; end if; if existing.version<>expected_version then raise exception 'This Maintenance relationship was changed elsewhere. Reload and try again.' using errcode='40001'; end if; if existing.status<>'active' then raise exception 'Only an Active Maintenance relationship can be paused' using errcode='22023'; end if; select count(*) into scheduled_count from public.maintenance_visits where maintenance_relationship_id=existing.id and status='scheduled'; if scheduled_count>0 then raise exception 'Resolve all Scheduled Maintenance visits before pausing this relationship' using errcode='22023'; end if; perform set_config('app.maintenance_relationship_controlled_transition','true',true); perform set_config('app.maintenance_relationship_transition_reason',coalesce(clean_reason,''),true); update public.maintenance_relationships set status='paused' where id=existing.id and version=expected_version returning * into existing; if not found then raise exception 'This Maintenance relationship was changed elsewhere. Reload and try again.' using errcode='40001'; end if; perform set_config('app.maintenance_relationship_controlled_transition','false',true); perform set_config('app.maintenance_relationship_transition_reason','',true); return existing; end$$;

create or replace function public.resume_maintenance_relationship(target_relationship_id uuid,expected_version integer)
returns public.maintenance_relationships language plpgsql security definer set search_path=pg_catalog,public as $$
declare existing public.maintenance_relationships;
begin select * into existing from public.maintenance_relationships where id=target_relationship_id for update; if not found then raise exception 'Maintenance relationship not found' using errcode='P0002'; end if; if not public.can_manage_maintenance_site(existing.site_id) then raise exception 'You are not authorised to manage this Maintenance relationship' using errcode='42501'; end if; if existing.version<>expected_version then raise exception 'This Maintenance relationship was changed elsewhere. Reload and try again.' using errcode='40001'; end if; if existing.status<>'paused' then raise exception 'Only a Paused Maintenance relationship can be resumed' using errcode='22023'; end if; perform set_config('app.maintenance_relationship_controlled_transition','true',true); update public.maintenance_relationships set status='active' where id=existing.id and version=expected_version returning * into existing; if not found then raise exception 'This Maintenance relationship was changed elsewhere. Reload and try again.' using errcode='40001'; end if; perform set_config('app.maintenance_relationship_controlled_transition','false',true); return existing; end$$;

create or replace function public.end_maintenance_relationship(target_relationship_id uuid,expected_version integer,reason text default null)
returns public.maintenance_relationships language plpgsql security definer set search_path=pg_catalog,public as $$
declare existing public.maintenance_relationships; clean_reason text:=nullif(trim(coalesce(reason,'')),''); open_scheduled_visits integer;
begin if public.current_user_role() is distinct from 'owner' then raise exception 'Only the Principal can end a Maintenance relationship' using errcode='42501'; end if; if clean_reason is null then raise exception 'A reason is required to end this Maintenance relationship' using errcode='22023'; end if; select * into existing from public.maintenance_relationships where id=target_relationship_id for update; if not found then raise exception 'Maintenance relationship not found' using errcode='P0002'; end if; if not public.can_manage_maintenance_site(existing.site_id) then raise exception 'You are not authorised to manage this Maintenance relationship' using errcode='42501'; end if; if existing.version<>expected_version then raise exception 'This Maintenance relationship was changed elsewhere. Reload and try again.' using errcode='40001'; end if; if existing.status='ended' then raise exception 'This Maintenance relationship has already ended' using errcode='22023'; end if; select count(*) into open_scheduled_visits from public.maintenance_visits where maintenance_relationship_id=existing.id and status='scheduled'; if open_scheduled_visits>0 then raise exception 'Resolve all scheduled Maintenance visits before ending this relationship' using errcode='22023'; end if; perform set_config('app.maintenance_relationship_controlled_transition','true',true); perform set_config('app.maintenance_relationship_transition_reason',clean_reason,true); update public.maintenance_relationships set status='ended' where id=existing.id and version=expected_version returning * into existing; perform set_config('app.maintenance_relationship_controlled_transition','false',true); perform set_config('app.maintenance_relationship_transition_reason','',true); perform set_config('app.maintenance_assignment_controlled_close','true',true); update public.maintenance_assignments set end_date=greatest(current_date,start_date) where maintenance_relationship_id=existing.id and end_date is null; perform set_config('app.maintenance_assignment_controlled_close','false',true); return existing; end$$;

create or replace function public.reschedule_maintenance_visit(target_visit_id uuid,expected_version integer,new_scheduled_date date)
returns public.maintenance_visits language plpgsql security definer set search_path=pg_catalog,public as $$
declare existing public.maintenance_visits; relationship public.maintenance_relationships;
begin if new_scheduled_date is null then raise exception 'A scheduled date is required' using errcode='22023'; end if; select * into existing from public.maintenance_visits where id=target_visit_id for update; if not found then raise exception 'Maintenance visit not found' using errcode='P0002'; end if; select * into relationship from public.maintenance_relationships where id=existing.maintenance_relationship_id for share; if not public.can_manage_maintenance_site(relationship.site_id) then raise exception 'You are not authorised to manage this Maintenance visit' using errcode='42501'; end if; if relationship.status<>'active' then raise exception 'A visit can only be rescheduled while Maintenance is Active' using errcode='22023'; end if; if existing.version<>expected_version then raise exception 'This Maintenance visit was changed elsewhere. Reload and try again.' using errcode='40001'; end if; if existing.status<>'scheduled' then raise exception 'Only a Scheduled visit can be rescheduled' using errcode='22023'; end if; perform set_config('app.maintenance_visit_controlled_transition','true',true); update public.maintenance_visits set scheduled_date=new_scheduled_date where id=existing.id and version=expected_version returning * into existing; perform set_config('app.maintenance_visit_controlled_transition','false',true); return existing; end$$;

create or replace function public.cancel_maintenance_visit(target_visit_id uuid,expected_version integer,cancellation_reason text)
returns public.maintenance_visits language plpgsql security definer set search_path=pg_catalog,public as $$
declare existing public.maintenance_visits; relationship public.maintenance_relationships; clean_reason text:=nullif(trim(coalesce(cancellation_reason,'')),'');
begin if clean_reason is null then raise exception 'A cancellation reason is required' using errcode='22023'; end if; select * into existing from public.maintenance_visits where id=target_visit_id for update; if not found then raise exception 'Maintenance visit not found' using errcode='P0002'; end if; select * into relationship from public.maintenance_relationships where id=existing.maintenance_relationship_id; if not public.can_manage_maintenance_site(relationship.site_id) then raise exception 'You are not authorised to manage this Maintenance visit' using errcode='42501'; end if; if existing.version<>expected_version then raise exception 'This Maintenance visit was changed elsewhere. Reload and try again.' using errcode='40001'; end if; if existing.status<>'scheduled' then raise exception 'Only a Scheduled visit can be cancelled' using errcode='22023'; end if; perform set_config('app.maintenance_visit_controlled_transition','true',true); perform set_config('app.maintenance_visit_transition_reason',clean_reason,true); update public.maintenance_visits set status='cancelled',cancellation_reason=clean_reason where id=existing.id and version=expected_version returning * into existing; perform set_config('app.maintenance_visit_controlled_transition','false',true); perform set_config('app.maintenance_visit_transition_reason','',true); return existing; end$$;

create or replace function public.complete_maintenance_visit_cycle(target_visit_id uuid,expected_version integer,target_daily_site_entry_id uuid,target_outcome text,completion_note text,target_follow_up_required boolean,target_follow_up_note text default null,next_scheduled_date date default null,next_purpose text default null)
returns public.maintenance_visits language plpgsql security definer set search_path=pg_catalog,public as $$
declare existing public.maintenance_visits; relationship public.maintenance_relationships; execution public.daily_site_entries; execution_site_id uuid; clean_note text:=nullif(trim(coalesce(completion_note,'')),''); clean_follow_up text:=nullif(trim(coalesce(target_follow_up_note,'')),''); clean_next_purpose text:=nullif(trim(coalesce(next_purpose,'')),'');
begin if target_outcome not in ('completed','partial') then raise exception 'Choose Completed or Partially completed for the Maintenance outcome' using errcode='22023'; end if; if clean_note is null then raise exception 'A short Maintenance completion note is required' using errcode='22023'; end if; if target_follow_up_required is null then raise exception 'State whether Maintenance follow-up is required' using errcode='22023'; end if; if target_outcome='partial' and not target_follow_up_required then raise exception 'Partially completed Maintenance requires follow-up' using errcode='22023'; end if; if target_follow_up_required and clean_follow_up is null then raise exception 'Describe the Maintenance follow-up required' using errcode='22023'; end if; if next_scheduled_date is not null and clean_next_purpose is null then raise exception 'Describe the planned work for the next Maintenance visit' using errcode='22023'; end if; select * into existing from public.maintenance_visits where id=target_visit_id for update; if not found then raise exception 'Maintenance visit not found' using errcode='P0002'; end if; select * into relationship from public.maintenance_relationships where id=existing.maintenance_relationship_id for share; if not public.can_manage_maintenance_site(relationship.site_id) then raise exception 'You are not authorised to manage this Maintenance visit' using errcode='42501'; end if; if existing.version<>expected_version then raise exception 'This Maintenance visit was changed elsewhere. Reload and try again.' using errcode='40001'; end if; if existing.status<>'scheduled' then raise exception 'Only a Scheduled visit can be completed' using errcode='22023'; end if;
 if target_daily_site_entry_id is not null then select * into execution from public.daily_site_entries where id=target_daily_site_entry_id; if not found then raise exception 'Daily Site Record not found' using errcode='P0002'; end if; select p.site_id into execution_site_id from public.projects p where p.id=execution.project_id; if execution_site_id is distinct from relationship.site_id then raise exception 'This Daily Site Record belongs to a different Site' using errcode='22023'; end if; if execution.work_date<>existing.scheduled_date then raise exception 'The Daily Site Record date must match the scheduled Maintenance visit date' using errcode='22023'; end if; if execution.state<>'accepted' then raise exception 'Only an Accepted Daily Site Record can close a Maintenance visit' using errcode='22023'; end if; end if;
 if next_scheduled_date is not null then if relationship.status<>'active' then raise exception 'A next visit can only be scheduled for Active Maintenance' using errcode='22023'; end if; if next_scheduled_date<=existing.scheduled_date then raise exception 'The next Maintenance visit must be after the visit being completed' using errcode='22023'; end if; end if; perform set_config('app.maintenance_visit_controlled_transition','true',true); update public.maintenance_visits set status='completed',completed_at=now(),completion_note=clean_note,daily_site_entry_id=target_daily_site_entry_id,completion_outcome=target_outcome,follow_up_required=target_follow_up_required,follow_up_note=case when target_follow_up_required then clean_follow_up else null end where id=existing.id and version=expected_version returning * into existing; perform set_config('app.maintenance_visit_controlled_transition','false',true); if next_scheduled_date is not null then insert into public.maintenance_visits(maintenance_relationship_id,scheduled_date,purpose) values(relationship.id,next_scheduled_date,clean_next_purpose); end if; return existing; end$$;

create or replace function public.end_maintenance_assignment(target_assignment_id uuid,expected_version integer)
returns public.maintenance_assignments language plpgsql security definer set search_path=pg_catalog,public as $$
declare existing public.maintenance_assignments; relationship public.maintenance_relationships;
begin select * into existing from public.maintenance_assignments where id=target_assignment_id for update; if not found then raise exception 'Maintenance assignment not found' using errcode='P0002'; end if; select * into relationship from public.maintenance_relationships where id=existing.maintenance_relationship_id; if not public.can_manage_maintenance_site(relationship.site_id) then raise exception 'You are not authorised to manage this Maintenance assignment' using errcode='42501'; end if; if existing.version<>expected_version then raise exception 'This assignment was changed elsewhere. Reload and try again.' using errcode='40001'; end if; if existing.end_date is not null then raise exception 'This assignment has already ended' using errcode='22023'; end if; perform set_config('app.maintenance_assignment_controlled_close','true',true); update public.maintenance_assignments set end_date=greatest(current_date,start_date) where id=existing.id and version=expected_version returning * into existing; perform set_config('app.maintenance_assignment_controlled_close','false',true); return existing; end$$;

create or replace function public.correct_maintenance_assignment(target_assignment_id uuid,expected_version integer,target_role text,target_start_date date,correction_reason text)
returns public.maintenance_assignments language plpgsql security definer set search_path=pg_catalog,public as $$
declare existing public.maintenance_assignments; corrected public.maintenance_assignments; relationship public.maintenance_relationships; clean_reason text:=nullif(trim(coalesce(correction_reason,'')),'');
begin if not public.is_owner() then raise exception 'Only the Principal may correct a Maintenance assignment' using errcode='42501'; end if; if clean_reason is null or char_length(clean_reason)<3 then raise exception 'Explain why this Maintenance assignment is being corrected' using errcode='22023'; end if; if char_length(clean_reason)>1000 then raise exception 'The correction reason must be 1000 characters or fewer' using errcode='22023'; end if; if target_role is null or target_role not in ('maintenance_lead','site_technician','inspector','supervisor','support') then raise exception 'Choose a valid Maintenance responsibility' using errcode='22023'; end if; if target_start_date is null then raise exception 'A start date is required' using errcode='22023'; end if; select * into existing from public.maintenance_assignments where id=target_assignment_id for update; if not found then raise exception 'Maintenance assignment not found' using errcode='P0002'; end if; select * into relationship from public.maintenance_relationships where id=existing.maintenance_relationship_id; if not public.can_manage_maintenance_site(relationship.site_id) then raise exception 'You are not authorised to manage this Maintenance assignment' using errcode='42501'; end if; if existing.version<>expected_version then raise exception 'This assignment was changed elsewhere. Reload and try again.' using errcode='40001'; end if; if existing.end_date is not null then raise exception 'This Maintenance assignment has ended and is historical; it cannot be corrected' using errcode='22023'; end if; perform set_config('app.maintenance_assignment_controlled_correction','true',true); perform set_config('app.maintenance_assignment_correction_reason',clean_reason,true); update public.maintenance_assignments set role=target_role,start_date=target_start_date where id=existing.id and version=expected_version returning * into corrected; perform set_config('app.maintenance_assignment_controlled_correction','false',true); perform set_config('app.maintenance_assignment_correction_reason','',true); return corrected; end$$;
